[http.middlewares.simpleAuth.basicAuth]
  users = [
    "user:passwordencrypt"
  ]

[http.routers.api]
  rule = "Host(`yourdomainforcontrolpaneltraefik`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
